---
- name: Understanding vars
  hosts: all
  become: yes
  gather_facts: false
  vars:
    USRNM: playuser
    COMM: variable for playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: usrout

    - debug:
        var: usrout.name

    - debug:
        var: usrout.comment
